services:
  db:
    image: postgres:15-alpine
    container_name: escolar_db_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: .
    container_name: escolar_api
    restart: always
    env_file: .env
    ports:
      - '${APPLICATION_PORT}:${APPLICATION_PORT}'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APPLICATION_PORT: ${APPLICATION_PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
